# deprecated
name: Docker build and push
description: Build and push docker image

inputs:
  path:
    description: context path to Dockerfile
    required: true
    default: ubuntu-basic

runs:
  using: composite
  steps:
    -
      name: lowercase username
      env:
        owner: ${{ github.repository_owner }}
      run: echo "user_lc=${owner,,}" >> ${GITHUB_ENV}
      shell: bash
    -
      name: Checkout
      uses: actions/checkout@v3
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.path }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.user_lc }}/${{ inputs.path }}:latest
          ghcr.io/${{ env.user_lc }}/${{ inputs.path }}:latest
