# A reusable workflow
name: Build and push docker

on:
  workflow_call:
    inputs:
      dir_path:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  reusable-build-push:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
      -
        name: lowercase username
        env:
          owner: ${{ github.repository_owner }}
        run: echo "user_lc=${owner,,}" >> ${GITHUB_ENV}
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.dir_path }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.user_lc }}/${{ inputs.name }}:latest
            ghcr.io/${{ env.user_lc }}/${{ inputs.name }}:latest
