name: ubuntu-basic

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/ubuntu-basic.yml
      - ubuntu-basic/**

jobs:
  ubuntu-basic:
    uses: .github/workflows/build_push_docker.yml@main
    with:
      path: ubuntu-basic
    secrets: inherit
