name: ubuntu-basic

on:
  push:
    branches:
      - 'main'
    paths:
      - ${{ github.workflow }}/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: ./.github/actions/build-push
        with:
          path: ${{ github.workflow }}
