name: ubuntu-python

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/ubuntu-python.yml
      - ubuntu-python/**
      - .github/workflows/build_push_docker.yml

jobs:
  ubuntu-python:
    uses: ./.github/workflows/build_push_docker.yml
    with:
      dir_path: ubuntu-python
      name: ubuntu-python
    secrets: inherit
