name: ubuntu-basic

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/ubuntu-basic.yml
      - .github/actions/build-push/**
      - ubuntu-basic/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: ./.github/actions/build-push
        with:
          path: ${{ github.workflow }}
