name: ubuntu-basic

on:
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/ubuntu-basic.yml
      - ubuntu-basic/**
      - .github/workflows/build_push_docker.yml

jobs:
  ubuntu-basic:
    uses: ./.github/workflows/build_push_docker.yml
    with:
      dir_path: ubuntu-basic
      name: ubuntu-basic
    secrets: inherit
